name = "PlantGeomPrimitives"
uuid = "7eef3cc5-4580-4ff0-8f6f-933507db6664"
authors = ["Alejandro Morales Sierra <alejandro.moralessierra@wur.nl> and contributors"]
version = "1.0.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Elliptic = "b305315f-e792-5b7a-8f41-49f472929428"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ArgCheck = "2.5.0"
CoordinateTransformations = "0.6.3"
Elliptic = "1.0.1"
FileIO = "1.16.1"
GeometryBasics = "0.5.10"
LinearAlgebra = "1.11"
MeshIO = "0.5.3"
Rotations = "1.5.1"
Sobol = "1.5.0"
StaticArrays = "1.5.25"
julia = "1.11"
